apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: longhorn-vservice
  namespace: longhorn-system
spec:
  gateways:
  - istio-system/istio-gateway
  hosts:
  - longhorn.conalep.mx
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: longhorn-frontend
