apiVersion: v1
kind: Service
metadata:
  name: apm-proxy
  labels:
    app: apm-proxy
spec:
  selector:
    app: apm-proxy
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apm-proxy
  labels:
    app: apm-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apm-proxy
  template:
    metadata:
      labels:
        app: apm-proxy
    spec:
      containers:
      - name: apm-proxy
        image: quay.io/oauth2-proxy/oauth2-proxy
        env:
        - name: OAUTH2_PROXY_PROVIDER
          value: "oidc"
        - name: OAUTH2_PROXY_CLIENT_ID
          value: "ops-proxy"
        - name: OAUTH2_PROXY_CLIENT_SECRET
          value: "3033b113-d108-4b12-b29b-79245cfb30f3"
        - name: OAUTH2_PROXY_OIDC_ISSUER_URL
          value: "https://login.ops.conalep.mx/auth/realms/conalep"
        - name: OAUTH2_PROXY_INSECURE_OIDC_ALLOW_UNVERIFIED_EMAIL
          value: "true"
        - name: OAUTH2_PROXY_REDIRECT_URL
          value: "https://apm.prueba.conalep.mx/oauth2/callback"
        - name: OAUTH2_PROXY_EMAIL_DOMAINS
          value: "*"
        - name: OAUTH2_PROXY_COOKIE_SECRET
          value: "1234567890098764"
        - name: OAUTH2_PROXY_UPSTREAMS
          value: "http://skywaking-ui:80"
        - name: OAUTH2_PROXY_HTTP_ADDRESS
          value: "0.0.0.0:8080"
