apiVersion: v1
kind: Service
metadata:
  name: longhorn-proxy
  labels:
    app: longhorn-proxy
spec:
  ports:
  - name: TCP
    port: 4180
  selector:
    app: longhorn-proxy
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: longhorn-proxy
  labels:
    app: longhorn-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: longhorn-proxy
  template:
    metadata:
      labels:
        app: longhorn-proxy
    spec:
      containers:
      - name: longhorn-proxy
        image: quay.io/oauth2-proxy/oauth2-proxy
        env:
        - name: OAUTH2_PROXY_PROVIDER
          value: "oidc"
        - name: OAUTH2_PROXY_CLIENT_ID
          value: "ops-proxy"
        - name: OAUTH2_PROXY_CLIENT_SECRET
          value: "3033b113-d108-4b12-b29b-79245cfb30f3"
        - name: OAUTH2_PROXY_OIDC_ISSUER_URL
          value: "https://login.ops.conalep.mx/auth/realms/conalep"
        - name: OAUTH2_PROXY_INSECURE_OIDC_ALLOW_UNVERIFIED_EMAIL
          value: "true"
        - name: OAUTH2_PROXY_REDIRECT_URL
          value: "https://longhorn.ops.conalep.mx/oauth2/callback"
        - name: OAUTH2_PROXY_EMAIL_DOMAINS
          value: "*"
        - name: OAUTH2_PROXY_COOKIE_SECRET
          value: "1234567890098765"
        - name: OAUTH2_PROXY_UPSTREAMS
          value: "http://longhorn-frontend.longhorn-system.svc.cluster.local"
