apiVersion: v1
kind: ConfigMap
metadata:
  name: s3proxy-config
data:
  S3PROXY_IDENTITY: "usuario"
  S3PROXY_CREDENTIAL: "contrasena"
  JCLOUDS_PROVIDER: "s3"
  JCLOUDS_IDENTITY: "QRIG7ZEINVECKJKB7PJI"
  JCLOUDS_CREDENTIAL: "gi0Ngrp7e2OL5PBukFeFAbY1fwZ0ZXOQnuTeCdAK"
  JCLOUDS_ENDPOINT: "obs.na-mexico-1.myhuaweicloud.com"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3proxy-deployment
  labels:
    app: s3proxy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: s3proxy
  template:
    metadata:
      labels:
        app: s3proxy
    spec:
      containers:
      - name: s3proxy
        image: andrewgaul/s3proxy
        ports:
        - containerPort: 80
        env:
        - name: S3PROXY_IDENTITY
          valueForm:
            configMapKeyRef:
              name: s3proxy-config
              key: S3PROXY_IDENTITY
        - name: S3PROXY_CREDENTIAL
          valueForm:
            configMapKeyRef:
              name: s3proxy-config
              key: S3PROXY_CREDENTIAL
        - name: JCLOUDS_PROVIDER
          valueForm:
            configMapKeyRef:
              name: s3proxy-config
              key: JCLOUDS_PROVIDER
        - name: JCLOUDS_IDENTITY
          valueForm:
            configMapKeyRef:
              name: s3proxy-config
              key: JCLOUDS_IDENTITY
        - name: JCLOUDS_CREDENTIAL
          valueForm:
            configMapKeyRef:
              name: s3proxy-config
              key: JCLOUDS_CREDENTIAL
    envFrom:
      - configMapRef:
          name: s3proxy-config
---
apiVersion: v1
kind: Service
metadata:
  name: s3proxy-service
spec:
  selector:
    app: s3proxy
  ports:
    - protocol: TCP
      port: 80
