apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-runner-config
  namespace: gitlab-runner
data:
  config.toml: |-
    concurrent = 30
    [[runners]]
      name = "Kubernetes Runner"
      url = "https://gitlab.dev.conalep.mx/"
      token = "aOut3EOS8bzAsxINa71yuojsCFWYTR3983W8PzA83EwfRPQBB7MZsJys5CoAxJvW"
      executor = "kubernetes"
      [runners.kubernetes]
        namespace = "gitlab-runner"
        poll_timeout = 600
        cpu_request = "1"
        service_cpu_request = "200m"
