apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: gitlab-dev-conalep
spec:
  chart:
    version: 5.6.3
    values:
      nginx-ingress:
        enabled: false
      global:
        hosts:
          domain: dev.conalep.mx
          https: false
        ingress:
          enabled: false
          class: nginx
          configureCertmanager: false
          tls:
            enabled: false
      certmanager:
        install: false
      gitlab-runner:
        install: false
