apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: gitlab-dev-conalep
spec:
  chart:
    # Provided <Operator Version> is the released version from 
    #  https://gitlab.com/gitlab-org/cloud-native/gitlab-operator/-/releases
    #  https://gitlab.com/gitlab-org/cloud-native/gitlab-operator/-/blob/<Operator Version>/CHART_VERSIONS
    version: 5.6.4
    values:
      nginx-ingress:
        enabled: false
      global:
        hosts:
          domain: dev.conalep.mx
          https: false
        ingress:
          enabled: false
          class: istio
          provider: istio
          configureCertmanager: false
          tls:
            enabled: false
      certmanager:
        install: false
      gitlab-runner:
        install: false
