apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: gitlab-vservice
  namespace: default
spec:
  gateways:
  - istio-system/istio-gateway
  hosts:
  - gitlab.dev.conalep.mx
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: gitlab-webservice-default
        port: 8181
  - match:
    - uri:
        prefix: /admin/sidekiq/
    route:
    - destination:
        host: gitlab-webservice-default
        port: 8080