---
apiVersion: v1
kind: Secret
data:
  miniocfg: "W2RlZmF1bHRdCmFjY2Vzc19rZXkgPSBhZG1jb25hbGVwCnNlY3JldF9rZXkgPSBDb25hbGVwMjAyMgo="
metadata:
  labels:
    app.kubernetes.io/name: miniocfg
  name: miniocfg
  namespace: curiefense
type: Opaque
---
apiVersion: v1
kind: Secret
data:
  miniocfg: "W2RlZmF1bHRdCmFjY2Vzc19rZXkgPSBhZG1jb25hbGVwCnNlY3JldF9rZXkgPSBDb25hbGVwMjAyMgo="
metadata:
  labels:
    app.kubernetes.io/name: miniocfg
  name: miniocfg
  namespace: istio-system
type: Opaque
