apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: argocd-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - argocd.ops.conalep.mx
    port:
      name: http
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true # sends 301 redirect for http requests
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: argocd-cert # This should match the Certificate secretName
    hosts:
    - argocd.ops.conalep.mx # This should match a DNS name in the Certificate
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: argocd-vservice
  namespace: argocd
spec:
  gateways:
  - argocd-gateway
  hosts:
  - argocd.ops.conalep.mx
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: argocd-server
